[package]
name = "sdl2-opengl-test"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[dependencies]
sdl2 = "0.30"
#TODO can this be a dev deependacy?
libloading = "0.4"
lazy_static = "0.2"

[dependencies.open_gl_bindings]
path = "./open_gl_bindings"

[dependencies.common]
path = "./common"
